### ISSUE TITLE
Question about the meaning of the notes in the test script for board.

### ISSUE THREAD

**Issue by Uio96** [ivapylibs/puzzle_solver#11]
The note is as follows:

>run display function
   plot piece locations in displayed image.
   hold on.
   mark with green + or something that pops
   image in first window and second window will be the same.

Here is my current result, not sure if that's what you want Or display two pieces in two windows instead?:
<img src="https://user-images.githubusercontent.com/13082153/127777941-97bf7396-919c-4ac7-af07-ab2916616062.png" width="300" height="300">

Link:
https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/testing/basic01_board.py#L82-L89

**Comment by pv33** [comment]
@Uio96 
I imagine that the code should do two things and test them:

1. Use display routine to display the puzzle board
2. Use the image insertion routine to synthesize an image.  Display this image in a window that is not the same as the window in the first bullet.

Through the two mechanisms to display or create graphical content, there are two visual outputs in two windows.  They should be the same.

**Comment by pv33** [comment]
@Uio96 
Please attach issues to a milestone if they are attached to work associated to a milestone. Make sure to attach to the Project also.  Lastly, make sure to update the Project kanban as appropriate.

Beyond Trello, git should be used to recurse or descend one more level of detail (towards more detail, from high level in Trello to low level in github).

The project and code management help to organize activities and effort so that one can visually asses the state of play.

**Comment by Uio96** [comment]
Solved by 2a9d852d64ea66eef0b4c8d5a1c4bbcd5da628f1
